import type { Metadata } from 'next'
import { ClerkProvider, GoogleOneTap, SignInButton, SignUpButton, SignedIn, SignedOut, UserButton, OrganizationSwitcher } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider signInUrl='/auth/login' signUpUrl='/auth/register' waitlistUrl='/waitlist'>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <nav className="flex flex-col sm:flex-row items-center justify-between bg-white shadow-md p-4">
            <OrganizationSwitcher organizationProfileMode='navigation' createOrganizationMode='navigation' createOrganizationUrl='/auth/organization/create' organizationProfileUrl='/auth/organization/profile' />
            <header className="flex justify-end items-center p-4 gap-4 h-16">
              <SignedOut>
                <SignInButton />
                <SignUpButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </header>
          </nav>
          {children}
          <GoogleOneTap />

        </body>
      </html>
    </ClerkProvider>
  )
}
